name: Monitor Website

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check Time and Skip if Between 12 AM - 6 AM IST
        id: check_time
        run: |
          CURRENT_HOUR=$(date -u +"%H")
          CURRENT_MINUTE=$(date -u +"%M")
          TIME_IN_MINUTES=$((CURRENT_HOUR * 60 + CURRENT_MINUTE))

          # 12 AM IST = 18:30 UTC, 6 AM IST = 00:30 UTC
          START_BLOCK_TIME=$((18 * 60 + 30))
          END_BLOCK_TIME=$((0 * 60 + 30))

          if [ "$TIME_IN_MINUTES" -ge "$START_BLOCK_TIME" ] || [ "$TIME_IN_MINUTES" -lt "$END_BLOCK_TIME" ]; then
            echo "skip=true" >> "$GITHUB_ENV"
          fi

      - name: Skip Remaining Steps if Out of Allowed Time Range
        if: env.skip == 'true'
        run: |
          echo "⏳ Skipping workflow as it's between 12 AM - 6 AM IST."
          exit 0

      - name: Checkout Repository
        uses: actions/checkout@v4
        if: env.skip != 'true'  # Ensures this step runs only if not skipped

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        if: env.skip != 'true'

      - name: Install Dependencies
        run: pip install requests twilio
        if: env.skip != 'true'

      - name: Run Website Monitor Script
        run: python monitor_website.py
        if: env.skip != 'true'
